const HOURS_IN_DAY = 24;
const DAY_HEADER_HEIGHT = 60;
const TIME_AXIS_WIDTH = 50;

const DEFAULT_HOUR_HEIGHT = 60;
const MIN_HOUR_HEIGHT = 40;
const MAX_HOUR_HEIGHT = 340;

const SCROLL_TOTAL_DAYS = 1000; // Total scrollable range
const SCROLL_TODAY_INDEX = 500;

export {
  HOURS_IN_DAY,
  DAY_HEADER_HEIGHT,
  TIME_AXIS_WIDTH,
  DEFAULT_HOUR_HEIGHT,
  MIN_HOUR_HEIGHT,
  MAX_HOUR_HEIGHT,
  SCROLL_TOTAL_DAYS,
  SCROLL_TODAY_INDEX,
};
